name: Terraform Runner Action
description: Action which does the github and aws setup to apply terraform plans
inputs:
  terraform-version:
    description: Terraform version to be used
    default: 1.1
  aws-cross-access-key-id:
    description: "TBD"
    required: true
  aws-cross-secret-access-key:
    description: "TBD"
    required: true
  aws-olx-prod-role:
    description: "TBD"
    required: true
  aws-olx-prod-role-external-id:
    description: "TBD"
    required: true
  token:
    description: "TBD"
    required: true
  aws-region:
    description: AWS region to be setup in the AWS credentials
    default: us-east-1
runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-cross-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-cross-secret-access-key }}
        role-duration-seconds: 1200
        role-to-assume: ${{ inputs.aws-ck-olx-prod-role }}
        role-external-id: ${{ inputs.aws-ck-olx-prod-role-external-id }}
        aws-region: ${{ inputs.aws-region }}

    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ inputs.terraform-version }}
    - uses: fusion-engineering/setup-git-credentials@v2
      with:
        credentials: https://ci:{{ inputs.token }}@github.com

    - name: Init
      run: |
        make init
      shell: bash

    - name: Plan
      run: |
        make plan
      shell: bash

    #- name: Appy
    #  run: |
    #    make apply
